:boom: initial commit of code
nhsuk/mongodb-updater pull request #1
Opened 2017-06-14 14:35 UTC by markysoft

2017-06-14 15:03 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-14 15:41 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-16 15:51 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-19 07:50 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-19 11:22 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-19 14:09 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-19 15:31 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-21 17:32 UTC, neilbmclaughlin submitted a review, later dismissed
LGTM. Couple of typos and a suggestion.

The ADR's were useful in elaborating on some of the work.

2017-06-21 17:32 UTC, neilbmclaughlin commented on .eslintrc.json
> +{
Raise issue to move to eslint package?

2017-06-21 17:32 UTC, neilbmclaughlin commented on README.md
> +This will set the `_id` for each record inserted to the value of the key.
I'm not clear when I might use this.  Could you add an example?

2017-06-21 17:32 UTC, neilbmclaughlin commented on README.md
> +This will set the `_id` for each record inserted to the value of the key.
It sounds like every document gets the _id.

2017-06-21 17:32 UTC, neilbmclaughlin commented on README.md
> +Note: the `index` may only bet set via a database config file, as it is a rich JSON object containing index keys and options.
Typo 'bet'

2017-06-22 09:34 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-22 10:34 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-22 10:44 UTC, st3v3nhunt requested changes
Nothing too important but a few comments/suggestions.

2017-06-22 10:44 UTC, st3v3nhunt commented on app.js
> +const schedule = require('node-schedule');
I've looked for an eslint rule to have requires for external modules to be above internal modules but I can't see one. It would be good if ln 3 was moved up on though.

2017-06-22 10:44 UTC, st3v3nhunt commented on lib/mongodb/dataImporter.js
> +      /* eslint-disable no-param-reassign */
The options are never turned back on in this file. Is that on purpose?

2017-06-22 10:44 UTC, st3v3nhunt commented on test/integration/fileHelper.js
> +
Remove extra line please.

2017-06-22 10:44 UTC, st3v3nhunt commented on test/integration/downloadFile.js
> +
Remove extra line please

2017-06-22 10:44 UTC, st3v3nhunt commented on lib/utils/fileHelper.js
> +module.exports = {
I'm surprised `eslint` hasn't picked up on there not being an additional blank line above this. Any chance of adding it please?

2017-06-22 10:44 UTC, st3v3nhunt commented on lib/mongodb/mongoWrapper.js
> +const MongoClient = require('mongodb').MongoClient;
Possibly move this to the first line as this seems to be convention.

2017-06-22 10:44 UTC, st3v3nhunt commented on lib/mongodb/dataImporter.js
> +
No need for this blank line. I wonder why `eslint` isn't picking this up?

2017-06-22 10:44 UTC, st3v3nhunt commented on lib/mongodb/dataImporter.js
> +      await this.mongoWrapper.createIndex(this.collection, index.keys, index.options);
Is it worth adding a log output here? The indexes seem like a process worth knowing a bit more about.

2017-06-22 12:34 UTC, c2s-dev commented
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-1.dev.beta.nhschoices.net)

2017-06-22 15:03 UTC, st3v3nhunt approved these changes
👍

2017-06-22 15:04 UTC, merged